language: r
os:
        - linux
        - osx
r:
        - release
        - devel
sudo: false
cache: packages
notifications:
  email:
    on_success: change
    on_failure: change
after_script: ./after.sh
